### ISSUE TITLE
Uhh errors

### ISSUE THREAD

**Issue by TheSatanicAngeI** [iBLiSSIN/survivio-plus#1]
> Uncaught TypeError: window.webpackJsonp is not a function
    at webpack_inject (webpack_override.js:48)
    at webpack_override.js:135
menuAppearance.js:180 Uncaught TypeError: Cannot read property 'ctrl' of undefined
    at btnSetBind (menuAppearance.js:180)
    at updateMenu (menuAppearance.js:245)
    at doWork (menuAppearance.js:374)
    at menu (menuAppearance.js:386)
    at menuAppearance.js:387

**Comment by TheSatanicAngeI** [comment]
> https://i.gyazo.com/ace95513fb38b141660ece45f5c0bb96.png

**Comment by iBLiSSIN** [comment]
Hey all cheat extensions is error guy! And this cheat is not work because the code of this cheat is very simple (not work for latest version game)

**Comment by humphreygaming** [comment]
You could just take SCI's var outputs and update them to this one probably and it might just work.
